"""Initial Migration

Revision ID: 46bfedffa0af
Revises: c1c5bf5376ce
Create Date: 2022-05-15 11:43:49.220671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46bfedffa0af'
down_revision = 'c1c5bf5376ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###
