"""Initial Migration

Revision ID: 7b86a9a299cd
Revises: 6ee89a416d65
Create Date: 2022-05-15 22:35:38.154972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b86a9a299cd'
down_revision = '6ee89a416d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.drop_column('comments', 'date_posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'date_created')
    # ### end Alembic commands ###
